INSERT INTO "Artists" ("Name", "Country")
VALUES
    ('Victor Tsoi', 'Russia'),
    ('Alla Pugacheva', 'Russia'),
    ('Igor Krutoy', 'Russia'),
    ('Philip Kirkorov', 'Russia'),
    ('Dima Bilan', 'Russia'),
    ('Larisa Dolina', 'Russia'),
    ('Sophia Rotaru', 'Ukraine'),
    ('Alexander Rosenbaum', 'Russia'),
    ('Irina Allegrova', 'Russia'),
    ('Grigory Leps', 'Russia'),
    ('Mikhail Shufutinsky', 'Russia'),
    ('Polina Gagarina', 'Russia'),
    ('Leonid Agutin', 'Russia'),
    ('Valery Meladze', 'Georgia'),
    ('Nikolay Baskov', 'Russia'),
    ('Yolka', 'Russia'),
    ('Max Barskykh', 'Ukraine'),
    ('Valeriya', 'Russia'),
    ('Glukoza', 'Russia'),
    ('Dmitry Malikov', 'Russia')
    ('Freddie Mercury', 'UK'),
    ('Ludwig van Beethoven', 'Germany'),
    ('Elton John', 'UK'),
    ('Céline Dion', 'Canada'),
    ('Shakira', 'Colombia'),
    ('Ravi Shankar', 'India'),
    ('Carlos Santana', 'Mexico'),
    ('Maria Callas', 'Greece'),
    ('Beyoncé', 'USA'),
    ('Luciano Pavarotti', 'Italy'),
    ('Fela Kuti', 'Nigeria'),
    ('Sezen Aksu', 'Turkey'),
    ('Bob Marley', 'Jamaica'),
    ('Yanni', 'Greece'),
    ('Ravi Shankar', 'India'),
    ('Andrea Bocelli', 'Italy'),
    ('Adele', 'UK'),
    ('Diana Krall', 'Canada'),
    ('Enrique Iglesias', 'Spain'),
    ('Zubin Mehta', 'India');